 window.texts = ["La început, Dumnezeu a făcut cerurile şi pământul. (Geneza 1:1)","Şi Dumnezeu a zis: Iată că v-am dat orice iarbă care face sămânţă şi care este pe faţa întregului pământ şi orice pom care are în el rod cu sămânţă: aceasta să fie hrana voastră. (Geneza 1:29)","Domnul Dumnezeu a făcut pe om din ţărâna pământului, i-a suflat în nări suflare de viaţă, şi omul s-a făcut astfel un suflet viu. (Geneza 2:7)",
"Vrăjmășie voi pune între tine și femeie, între sămânţa ta și sămânţa ei. Aceasta îţi va zdrobi capul, și tu îi vei zdrobi călcâiul. (Geneza 3:15)",
"Nu-i aşa? Dacă faci bine, vei fi bine primit; dar dacă faci rău, păcatul pândeşte la uşă; dorinţa lui se ţine după tine, dar tu să-l stăpâneşti. (Geneza 4:7)",
"Voi face din tine un neam mare şi te voi binecuvânta; îţi voi face un nume mare şi vei fi o binecuvântare. (Geneza 12:2)",
"nu te teme; Eu sunt scutul tău şi răsplata ta cea foarte mare. (Geneza 15:1 u.p.)",
"Eu sunt Dumnezeul cel Atotputernic. Umblă înaintea Mea şi fii fără prihană. (Geneza 17:1 u.p.)",
"Voi face un legământ între Mine şi tine şi te voi înmulţi nespus de mult. (Geneza 17:2)",
"Dumnezeu este cu tine în tot ce faci. (Geneza 21:22 u.p.)","Toate neamurile pământului vor fi binecuvântate în sămânţa ta, pentru că ai ascultat de porunca Mea! (Geneza 22:18)",
"Isaac a făcut semănături în ţara aceea şi a strâns rod însutit în anul acela; căci Domnul l-a binecuvântat. Astfel omul acesta s-a îmbogăţit şi a mers îmbogăţindu-se din ce în ce mai mult, până ce a ajuns foarte bogat. (Geneza 26:12,13)",
"Domnul i S-a arătat chiar în noaptea aceea şi i-a zis: „Eu sunt Dumnezeul tatălui tău, Avraam; nu te teme, căci Eu sunt cu tine; te voi binecuvânta şi îţi voi înmulţi sămânţa, din pricina robului Meu, Avraam.” (Geneza 26:24)",
"Iată, Eu sunt cu tine; te voi păzi pretutindeni pe unde vei merge şi te voi aduce înapoi în ţara aceasta; căci nu te voi părăsi, până nu voi împlini ce-ţi spun. (Geneza 28:15)",
"Fiţi pe pace! Nu vă temeţi de nimic. (Geneza 43:23 p.p.)",
"Domnul Se va lupta pentru voi; dar voi staţi liniştiţi. (Exod 14:14)",
"Domnul este tăria mea şi temeiul cântărilor mele de laudă: El m-a scăpat. El este Dumnezeul meu: pe El Îl voi lăuda; El este Dumnezeul tatălui meu: pe El Îl voi preamări. Domnul este un războinic viteaz: numele Lui este Domnul. (Exod 15:2-3)",
"Cine este ca Tine între dumnezei, Doamne? Cine este ca Tine minunat în sfinţenie, bogat în fapte de laudă, şi făcător de minuni? (Exod 15:11)",
"Prin îndurarea Ta, Tu ai călăuzit şi ai izbăvit pe poporul acesta; iar prin puterea Ta îl îndrepţi spre locaşul sfinţeniei Tale. (Exod 15:13)",
"Tu îi vei aduce şi-i vei aşeza pe muntele moştenirii Tale, în locul pe care Ţi l-ai pregătit ca locaş, Doamne, la Templul pe care mâinile Tale l-au întemeiat, Doamne! (Exod 15:17)",
'El a zis: "Dacă vei asculta cu luare aminte glasul Domnului Dumnezeului tău, dacă vei face ce este bine înaintea Lui, dacă vei asculta de poruncile Lui şi dacă vei păzi toate legile Lui, nu te voi lovi cu niciuna din bolile cu care am lovit pe egipteni; căci Eu sunt Domnul care te vindecă." (Exod 15:26)','"Cunosc acum că Domnul este mai mare decât toţi dumnezeii; căci în lucrul în care s-au purtat cu trufie, El a fost mai presus de ei." (Exod 18:11)', "Acum, dacă veţi asculta glasul Meu şi dacă veţi păzi legământul Meu, veţi fi ai Mei dintre toate popoarele, căci tot pământul este al Meu. (Exod 19:5)",
"Eu sunt Domnul Dumnezeul tău care te-a scos din ţara Egiptului, din casa robiei. Să nu ai alţi dumnezei afară de Mine. (Exod 20:2,3)",
"Să nu iei în deşert Numele Domnului Dumnezeului tău; căci Domnul nu va lăsa nepedepsit pe cel ce va lua în deşert Numele Lui. (Exod 20:7)",
"Cinsteşte pe tatăl tău şi pe mama ta, pentru ca să ţi se lungească zilele în ţara pe care ţi-o dă Domnul Dumnezeul tău. (Exod 20:12)",
"Să nu ucizi. Să nu preacurveşti. Să nu furi. (Exod 20:13-15)",
"Să nu mărturiseşti strâmb împotriva aproapelui tău. (Exod 20:16)",
"Să nu-ţi faci chip cioplit, nici vreo înfăţişare a lucrurilor care sunt sus în ceruri, sau jos pe pământ, sau în apele mai de jos decât pământul. Să nu te închini înaintea lor şi să nu le slujeşti; căci Eu, Domnul Dumnezeul tău, sunt un Dumnezeu gelos, care pedepsesc nelegiuirea părinţilor în copii, până la al treilea şi la al patrulea neam al celor ce Mă urăsc, şi Mă îndur până la al miilea neam de cei ce Mă iubesc şi păzesc poruncile Mele. (Exod 20:4-6)",
"Adu-ţi aminte de ziua de odihnă, ca s-o sfinţeşti. Să lucrezi şase zile şi să-ţi faci lucrul tău. Dar ziua a şaptea este ziua de odihnă închinată Domnului Dumnezeului tău: să nu faci nicio lucrare în ea, nici tu, nici fiul tău, nici fiica ta, nici robul tău, nici roaba ta, nici vita ta, nici străinul care este în casa ta. Căci în şase zile a făcut Domnul cerurile, pământul şi marea, şi tot ce este în ele, iar în ziua a şaptea S-a odihnit: de aceea a binecuvântat Domnul ziua de odihnă şi a sfinţit-o. (Exod 20:8-11)",
"Să nu pofteşti casa aproapelui tău; să nu pofteşti nevasta aproapelui tău, nici robul lui, nici roaba lui, nici boul lui, nici măgarul lui, nici vreun alt lucru care este al aproapelui tău. (Exod 20:17)", 'Moise a zis poporului: "Nu vă înspăimântaţi; căci Dumnezeu a venit tocmai ca să vă pună la încercare şi ca să aveţi frica Lui înaintea ochilor voştri, pentru ca să nu păcătuiţi." (Exod 20:20)',
"Să nu faceţi dumnezei de argint şi dumnezei de aur, ca să-i puneţi alături de Mine; să nu vă faceţi alţi dumnezei. (Exod 20:23)",
"Dar dacă vei asculta glasul Lui şi dacă vei face tot ce-ţi voi spune, Eu voi fi vrăjmaşul vrăjmaşilor tăi şi potrivnicul potrivnicilor tăi. (Exod 23:22)",
"Voi să slujiţi Domnului Dumnezeului vostru, şi El vă va binecuvânta pâinea şi apele, şi voi îndepărta boala din mijlocul tău. (Exod 23:25)",
"Nu va fi în ţara ta nici femeie care să-şi lepede copilul, nici femeie stearpă. Numărul zilelor tale îl voi face să fie deplin. (Exod 23:26)",
"Vorbeşte copiilor lui Israel şi spune-le: „Să nu care cumva să nu ţineţi Sabatele Mele, căci acesta va fi între Mine şi voi şi urmaşii voştri un semn după care se va cunoaşte că Eu sunt Domnul, care vă sfinţesc”. (Exod 31:13)",
"Să ţineţi Sabatul, căci el va fi pentru voi ceva sfânt. Cine îl va călca va fi pedepsit cu moartea; cine va face vreo lucrare în ziua aceasta va fi nimicit din mijlocul poporului său. (Exod 31:14)",
"Să lucrezi şase zile; dar a şaptea este Sabatul, ziua de odihnă închinată Domnului. Cine va face vreo lucrare în ziua Sabatului va fi pedepsit cu moartea. (Exod 31:15)",
"Copiii lui Israel să păzească Sabatul, prăznuindu-l, ei şi urmaşii lor, ca un legământ necurmat. (Exod 31:16)",
"Du-te, dar, şi du poporul unde ţi-am spus. Iată, Îngerul Meu va merge înaintea ta, dar în ziua răzbunării Mele, îi voi pedepsi pentru păcatul lor! (Exod 32:34)",
"Domnul a răspuns: „Voi merge Eu însumi cu tine şi îţi voi da odihnă.” (Exod 33:14)","Domnul a răspuns: „Voi face să treacă pe dinaintea ta toată frumuseţea Mea şi voi chema Numele Domnului înaintea ta; Eu Mă îndur de cine vreau să Mă îndur şi am milă de cine vreau să am milă!” (Exod 33:19)",
'Şi Domnul a trecut pe dinaintea lui şi a strigat: "Domnul Dumnezeu este un Dumnezeu plin de îndurare şi milostiv, încet la mânie, plin de bunătate şi credincioşie, care Îşi ţine dragostea până în mii de neamuri de oameni, iartă fărădelegea, răzvrătirea şi păcatul, dar nu socoteşte pe cel vinovat drept nevinovat, şi pedepseşte fărădelegea părinţilor în copii şi în copiii copiilor lor până la al treilea şi al patrulea neam!" (Exod 34:6, 7)',
'Domnul a răspuns: "Iată, Eu fac un legământ. Voi face, în faţa întregului popor, minuni care n-au avut loc în nicio ţară şi la niciun neam; tot poporul care este în jurul tău va vedea lucrarea Domnului, şi prin tine voi face lucruri înfricoşate." (Exod 34:10)', "Să nu te închini înaintea unui alt dumnezeu; căci Domnul se numeşte gelos, este un Dumnezeu gelos. (Exod 34:14)",
"Să nu-ţi faci un dumnezeu turnat. (Exod 34:17)",
"Şase zile să lucrezi, iar în ziua a şaptea să te odihneşti; să te odihneşti, chiar în vremea aratului şi seceratului. (Exod 34:21)", 'Moise a zis: "Să faceţi ce a poruncit Domnul; şi vi se va arăta slava Domnului." (Levitic 9:6)',
"Căci Eu sunt Domnul, care v-am scos din ţara Egiptului ca să fiu Dumnezeul vostru, şi să fiţi sfinţi; căci Eu sunt sfânt. (Levitic 11:45)",
"Fiţi sfinţi, căci Eu sunt sfânt, Eu, Domnul Dumnezeul vostru. (Levitic 19:2 u.p.)",
"Voi da pace în ţară, şi nimeni nu vă va tulbura somnul; voi face să piară din ţară fiarele sălbatice, şi sabia nu va trece prin ţara voastră. (Levitic 26:6)",
"Îmi voi aşeza Locaşul Meu în mijlocul vostru, şi sufletul Meu nu vă va urî. (Levitic 26:11)",
"Voi umbla în mijlocul vostru; Eu voi fi Dumnezeul vostru, şi voi veţi fi poporul Meu. (Levitic 26:12)",
"Eu sunt Domnul Dumnezeul vostru care v-am scos din ţara Egiptului, care v-am scos din robie; Eu am rupt legăturile jugului vostru şi v-am făcut să mergeţi cu capul ridicat. (Levitic 26:13)", "Domnul să te binecuvânteze şi să te păzească! Domnul să facă să lumineze faţa Lui peste tine şi să Se îndure de tine! Domnul să-Şi înalţe faţa peste tine şi să-ţi dea pacea! (Numeri 6:24-26)",
'Domnul a răspuns lui Moise: "Nu cumva s-a scurtat oare mâna Domnului? Vei vedea acum dacă ceea ce ţi-am spus se va întâmpla sau nu." (Numeri 11:23)',
"Dumnezeu nu este un om ca să mintă, nici un fiu al omului, ca să-I pară rău. Ce a spus, oare nu va face? Ce a făgăduit, oare nu va împlini? (Numeri 23:19)", "Iată că Domnul Dumnezeul tău îţi pune ţara înainte; suie-te, ia-o în stăpânire, cum ţi-a spus Domnul Dumnezeul părinţilor tăi; nu te teme şi nu te înspăimânta. (Deuteronom 1:21)",
"Domnul Dumnezeul vostru care merge înaintea voastră, Se va lupta El însuşi pentru voi, potrivit cu tot ce a făcut pentru voi sub ochii voştri în Egipt. (Deuteronom 1:30)",
"Căci Domnul Dumnezeul tău te-a binecuvântat în tot lucrul mâinilor tale şi ţi-a cunoscut călătoria în acest mare pustiu. Iată, de patruzeci de ani de când Domnul Dumnezeul tău este cu tine, şi n-ai dus lipsă de nimic. (Deuteronom 2:7)",
"Nu te teme de ei; căci Domnul Dumnezeul vostru va lupta El însuși pentru voi. (Deuteronom 3:22)",
"Şi după ce ţi se vor întâmpla toate aceste lucruri în strâmtorarea ta, în zilele de pe urmă, te vei întoarce la Domnul Dumnezeul tău şi vei asculta glasul Lui; căci Domnul Dumnezeul tău este un Dumnezeu plin de îndurare, care nu te va părăsi şi nu te va nimici; El nu va uita legământul pe care l-a încheiat prin jurământ cu părinții tăi. (Deuteronom 4:30-31)",
"Şi poruncile acestea, pe care ţi le dau astăzi, să le ai în inima ta. (Deuteronom 6:6)",
"Domnul va depărta de tine orice boală; nu-ţi va trimite niciuna din acele molime rele din Egipt, pe care le cunoști, ci va lovi cu ele pe toţi cei ce te urăsc. (Deuteronom 7:15)",
"ci să-i dai şi să nu dai cu părere de rău în inimă; căci pentru aceasta te va binecuvânta Domnul Dumnezeul tău în toate lucrările de care te vei apuca. (Deuteronom 15:10)",
"Să le spună: „Ascultă, Israele! Voi astăzi sunteţi aproape de luptă împotriva vrăjmaşilor voştri. Să nu vi se tulbure inima, fiţi fără teamă, nu vă înspăimântaţi, nu vă îngroziţi dinaintea lor. Căci Domnul Dumnezeul vostru merge cu voi, ca să bată pe vrăjmaşii voştri, ca să vă mântuiască.” (Deuteronom 20:3,4)",
"Dacă vei asculta de glasul Domnului Dumnezeului tău păzind şi împlinind toate poruncile Lui pe care ţi le dau astăzi, Domnul Dumnezeul tău îţi va da întâietate asupra tuturor neamurilor de pe pământ. (Deuteronom 28:1)","Domnul te va face să fii cap, nu coadă; întotdeauna vei fi sus, şi niciodată nu vei fi jos, dacă vei asculta de poruncile Domnului Dumnezeului tău pe care ţi le dau astăzi, dacă le vei păzi şi le vei împlini şi nu te vei abate nici la dreapta, nici la stânga de la toate poruncile pe care vi le dau astăzi, ca să vă duceţi după alţi dumnezei şi să le slujiţi. (Deuteronom 28:13,14)",
"Domnul Dumnezeul tău te va umple de bunătăţi, făcând să propăşească tot lucrul mâinilor tale, rodul trupului tău, rodul turmelor tale şi rodul pământului tău; căci Domnul Se va bucura din nou de fericirea ta, cum Se bucura de fericirea părinţilor tăi, dacă vei asculta de glasul Domnului Dumnezeului tău păzind poruncile şi rânduielile Lui scrise în cartea aceasta a Legii, dacă te vei întoarce la Domnul Dumnezeul tău din toată inima ta şi din tot sufletul tău. (Deuteronom 30:9,10)",
"Întăriţi-vă şi îmbărbătaţi-vă! Nu vă temeţi şi nu vă înspăimântaţi de ei, căci Domnul Dumnezeul tău va merge El însuşi cu tine, nu te va părăsi şi nu te va lăsa. (Deuteronom 31:6)","Domnul însuşi va merge înaintea ta, El însuşi va fi cu tine, nu te va părăsi şi nu te va lăsa; nu te teme şi nu te înspăimânta! (Deuteronom 31:8)",
"Ca ploaia să curgă învăţăturile mele, ca roua să cadă cuvântul meu, ca ploaia repede pe verdeaţă, ca picăturile de ploaie pe iarbă! (Deuteronom 32:2)",
"El este Stânca; lucrările Lui sunt desăvârşite, căci toate căile Lui sunt drepte; El este un Dumnezeu credincios şi fără nedreptate, El este drept şi curat. (Deuteronom 32:4)",
"Nimeni nu este ca Dumnezeul lui Israel, El trece pe ceruri ca să-ţi vină în ajutor, trece cu măreţie pe nori. (Deuteronom 33:26)",
"Dumnezeul cel Veşnic este un loc de adăpost, şi sub braţele Lui cele veşnice este un loc de scăpare. El a izgonit pe vrăjmaş dinaintea ta şi a zis: „Nimiceşte-l.” (Deuteronom 33:27)","Orice loc pe care-l va călca talpa piciorului vostru vi-l dau, cum am spus lui Moise. (Iosua 1:3)",
"Nimeni nu va putea să stea împotriva ta, cât vei trăi. Eu voi fi cu tine, cum am fost cu Moise; nu te voi lăsa, nici nu te voi părăsi. (Iosua 1:5)",
"Cartea aceasta a Legii să nu se depărteze de gura ta; cugetă asupra ei zi şi noapte, căutând să faci tot ce este scris în ea; căci atunci vei izbândi în toate lucrările tale şi atunci vei lucra cu înţelepciune. (Iosua 1:8)",
"Nu ţi-am dat Eu oare porunca aceasta: „Întăreşte-te şi îmbărbătează-te”? Nu te înspăimânta şi nu te îngrozi, căci Domnul Dumnezeul tău este cu tine în tot ce vei face. (Iosua 1:9)",
'Iosua a zis: "Prin aceasta veţi cunoaşte că Dumnezeul cel Viu este în mijlocul vostru şi că va izgoni dinaintea voastră pe canaaniţi, pe hetiţi, pe heviţi, pe fereziţi, pe ghirgasiţi, pe amoriţi şi pe iebusiţi. (Iosua 3:10)',"Vegheaţi, dar, cu luare aminte asupra sufletelor voastre, ca să iubiţi pe Domnul, Dumnezeul vostru. (Iosua 23:11)",'"Aşa să piară toţi vrăjmaşii Tăi, Doamne! Dar cei ce-L iubesc sunt ca soarele, când se arată în puterea lui." Ţara a avut odihnă patruzeci de ani. (Judecători 5:31)"','Îngerul Domnului i S-a arătat şi i-a zis: "Domnul este cu tine, viteazule!" (Judecători 6:12)',"Domnul să-ţi răsplătească ce ai făcut, şi plata să-ţi fie deplină din partea Domnului Dumnezeului lui Israel sub ale cărui aripi ai venit să te adăposteşti! (Rut 2:12)","Nimeni nu este sfânt ca Domnul; nu este alt Dumnezeu decât Tine; nu este stâncă aşa ca Dumnezeul nostru. (1 Samuel 2:2)",
"Nu mai vorbiţi cu atâta îngâmfare, să nu vă mai iasă din gură cuvinte de mândrie; căci Domnul este un Dumnezeu care ştie totul, şi toate faptele sunt cântărite de El. (1 Samuel 2:3)",
"Domnul omoară şi învie, El coboară în Locuinţa morţilor şi El scoate de acolo. Domnul sărăceşte şi El îmbogăţeşte, El smereşte şi El înalţă, El ridică din pulbere pe cel sărac, ridică din gunoi pe cel lipsit. Ca să-i pună să şadă alături cu cei mari. Şi le dă de moştenire un scaun de domnie îmbrăcat cu slavă; căci ai Domnului sunt stâlpii pământului şi pe ei a aşezat El lumea. (1 Samuel 2:6-8)",
"El va păzi paşii preaiubiţilor Lui, dar cei răi vor fi nimiciţi în întuneric; căci omul nu va birui prin putere. (1 Samuel 2:9)",
"Vrăjmaşii Domnului vor tremura, din înălţimea cerului El Îşi va arunca tunetul asupra lor; Domnul va judeca marginile pământului. El va da Împăratului Său putere şi El va înălţa tăria Unsului Lui. (1 Samuel 2:10)",
'De aceea, iată ce zice Domnul Dumnezeul lui Israel: "Spusesem că şi casa ta şi casa tatălui tău au să umble întotdeauna înaintea Mea." Şi acum, zice Domnul, departe de Mine lucrul acesta! Căci voi cinsti pe cine Mă cinsteşte, dar cei ce Mă dispreţuiesc vor fi dispreţuiţi. (1 Samuel 2:30)',
"Dacă vă veţi teme de Domnul, dacă-I veţi sluji, dacă veţi asculta de glasul Lui şi dacă nu vă veţi împotrivi cuvântului Domnului, vă veţi alipi de Domnul Dumnezeul vostru, atât voi cât şi împăratul care domneşte peste voi. (1 Samuel 12:14)",
"Acum mai aşteptaţi aici ca să vedeţi minunea pe care o va face Domnul sub ochii voştri. (1 Samuel 12:16)",
"Nu vă abateţi de la El; altfel, aţi merge după lucruri de nimic, care n-aduc nici folos, nici izbăvire, pentru că sunt lucruri de nimic. (1 Samuel 12:21)",
"Domnul nu va părăsi pe poporul Lui, din pricina Numelui Lui celui mare, căci Domnul a hotărât să facă din voi poporul Lui. (1 Samuel 12:22)", 'Samuel a zis: "Îi plac Domnului mai mult arderile de tot şi jertfele decât ascultarea de glasul Domnului? Ascultarea face mai mult decât jertfele, şi păzirea cuvântului Său face mai mult decât grăsimea berbecilor. (1 Samuel 15:22)',
'Şi Domnul a zis lui Samuel: "Nu te uita la înfăţişarea şi înălţimea staturii lui, căci l-am lepădat. Domnul nu Se uită la ce se uită omul; omul se uită la ceea ce izbeşte ochii, dar Domnul Se uită la inimă." (1 Samuel 16:7)',
'Şi David a întrebat pe Domnul: "Să urmăresc oastea aceasta? O voi ajunge?" Domnul i-a răspuns: "Urmăreşte-o, căci o vei ajunge şi vei izbăvi totul." (1 Samuel 30:8)',"David ajungea tot mai mare, şi Domnul Dumnezeul oştirilor era cu el. (2 Samuel 5:10)",'Şi Dumnezeu a zis: "Fiindcă lucrul acesta îl ceri, fiindcă nu ceri pentru tine nici viaţă lungă, nici bogăţii, nici moartea vrăjmaşilor tăi, ci ceri pricepere, ca să faci dreptate, voi face după cuvântul tău. Îţi voi da o inimă înţeleaptă şi pricepută, aşa cum n-a fost nimeni înaintea ta şi nu se va scula nimeni niciodată ca tine. Mai mult, îţi voi da şi ce n-ai cerut: bogăţii şi slavă, aşa încât în tot timpul vieţii tale nu va fi niciun împărat ca tine. (1 Împărați 3:11-13)',
"Şi dacă vei umbla în căile Mele, păzind legile şi poruncile Mele, cum a făcut David, tatăl tău, îţi voi lungi zilele. (1 Împărați 3:14)",
"ascultă din ceruri, din locul locuinţei Tale, rugăciunile şi cererile lor: şi fă-le dreptate. (1 Împărați 8:49)",
"iartă poporului Tău păcatele lui şi toate fărădelegile făcute împotriva Ta; trezeşte mila celor ce-i vor ţine robi, ca să se îndure de ei. (1 Împărați 8:50)",
"Domnul Dumnezeul nostru să fie cu noi, cum a fost cu părinţii noştri; să nu ne părăsească şi să nu ne lase, ci să ne plece inimile spre El, ca să umblăm în toate căile Lui şi să păzim poruncile Lui, legile Lui şi rânduielile Lui, pe care le-a poruncit părinţilor noştri! (1 Împărați 8:57,58)",
"Inima voastră să fie în totul a Domnului Dumnezeului nostru, cum este astăzi, ca să urmaţi legile Lui şi să păziţi poruncile Lui. (1 Împărați 8:61)","Dar ştiu când stai jos, când ieşi şi când intri şi când eşti furios împotriva Mea. (2 Împărați 19:27)","Eu îi voi fi Tată, şi el Îmi va fi fiu; şi nu voi îndepărta bunătatea Mea de la el, cum am îndepărtat-o de la cel dinaintea ta. (1 Cronici 17:13)",
"Îl voi aşeza pentru totdeauna în Casa Mea, şi în Împărăţia Mea scaunul lui de domnie va fi întărit pe vecie. (1 Cronici 17:14)",
'Şi împăratul David s-a dus şi s-a înfăţişat înaintea Domnului şi a zis: "Cine sunt eu, Doamne Dumnezeule, şi ce este casa mea, de m-ai făcut să ajung unde sunt?" (1 Cronici 17:16)','Doamne, din pricina robului Tău şi după inima Ta, ai făcut aceste lucruri mari şi i le-ai descoperit. (1 Cronici 17:19)","Doamne! Nimeni nu este ca Tine şi nu este alt Dumnezeu afară de Tine, după tot ce am auzit cu urechile noastre. (1 Cronici 17:20)',
"Acum, Doamne, Tu eşti adevăratul Dumnezeu şi Tu ai vestit harul acesta robului Tău. (1 Cronici 17:26)",
'Binecuvântă, dar, casa robului Tău, ca să rămână pe vecie înaintea Ta! Căci ce binecuvântezi Tu, Doamne, este binecuvântat pentru veşnicie!" (1 Cronici 17:27)',"Atunci vei propăşi, dacă vei căuta să împlineşti legile şi poruncile pe care le-a dat lui Moise, Domnul pentru Israel. Întăreşte-te şi îmbărbătează-te, nu te teme şi nu te înspăimânta. (1 Cronici 22:13)",'Dumnezeu a zis lui Solomon: "Fiindcă dorinţa aceasta este în inima ta, fiindcă nu ceri nici bogăţii, nici averi, nici slavă, nici moartea vrăjmaşilor tăi, nici chiar o viaţă lungă, ci ceri pentru tine înţelepciune şi pricepere ca să judeci pe poporul Meu, peste care te-am pus să domneşti, înţelepciunea şi priceperea îţi sunt date. Îţi voi da, pe deasupra, bogăţii, averi şi slavă, cum n-a mai avut niciodată niciun împărat înaintea ta şi cum nici nu va mai avea după tine." (2 Cronici 1:11,12)',
"voi, dar, întăriţi-vă şi nu lăsaţi să vă slăbească mâinile, căci faptele voastre vor avea o răsplată. (2 Cronici 15:7)",
"Şi Iahaziel a zis: „Ascultaţi, tot Iuda şi locuitorii din Ierusalim, şi tu, împărate Iosafat! Aşa vă vorbeşte Domnul: „Nu vă temeţi şi nu vă înspăimântaţi dinaintea acestei mari mulţumi, căci nu voi veţi lupta, ci Dumnezeu.”” (2 Cronici 20:15)",
'"Întăriţi-vă şi îmbărbătaţi-vă. Nu vă temeţi şi nu vă înspăimântaţi înaintea împăratului Asiriei şi înaintea întregii mulţimi care este cu el; căci cu noi sunt mai mulţi decât cu el. Cu el este un braţ de carne, dar cu noi este Domnul Dumnezeul nostru care ne va ajuta şi va lupta pentru noi.” Poporul a avut încredere în cuvintele lui Ezechia, împăratul lui Iuda. " (2 Cronici 32:7,8)',
 "Acest Ezra a venit din Babilon: era un cărturar iscusit în Legea lui Moise, dată de Domnul, Dumnezeul lui Israel. Şi, fiindcă mâna Domnului, Dumnezeului său, era peste el, împăratul i-a dat tot ce ceruse. ( Ezra 7:6)",
"Căci Ezra îşi pusese inima să adâncească şi să împlinească Legea Domnului, şi să înveţe pe oameni în mijlocul lui Israel legile şi poruncile. (Ezra 7:10)",
 "Mâna Dumnezeului nostru este, spre binele lor, peste toţi cei ce-L caută, dar puterea şi mânia Lui sunt peste toţi cei ce-L părăsesc. ( Ezra 8:22 up)",
"Dumnezeule, sunt uluit şi mi-e ruşine, Dumnezeule, să-mi ridic faţa spre Tine. Căci fărădelegile noastre s-au înmulţit deasupra capetelor noastre, şi greşelile noastre au ajuns până la ceruri. (Ezra 9:6)",
"Doamne, Dumnezeul lui Israel, Tu eşti drept, căci astăzi noi suntem o rămăşiţă de robi izbăviţi. Iată-ne înaintea Ta ca nişte vinovaţi şi din această pricină nu putem sta înaintea Ta. ( Ezra 9:15)", "dar, dacă vă veţi întoarce la Mine şi dacă veţi păzi poruncile Mele şi le veţi împlini, atunci, chiar dacă veţi fi izgoniţi la marginea cea mai depărtată a cerului, de acolo vă voi aduna şi vă voi aduce iarăşi în locul pe care l-am ales ca să locuiască Numele Meu acolo. ( Neemia 1:9)",
"Adu-Ţi aminte de mine, spre bine, Dumnezeule, pentru tot ce am făcut pentru poporul acesta! (Neemia 5:19)",
"Ei citeau desluşit în cartea Legii lui Dumnezeu şi-i arătau înţelesul, ca să-i facă să înţeleagă ce citiseră. (Neemia 8:8)","Sculaţi-vă şi binecuvântaţi pe Domnul, Dumnezeul vostru, din veşnicie în veşnicie! Binecuvântat să fie Numele Tău cel slăvit, care este mai presus de orice binecuvântare şi de orice laudă! ( Neemia 9:5up)",
"Tu, Doamne, numai Tu ai făcut cerurile, cerurile cerurilor şi toată oştirea lor şi pământul cu tot ce este pe el, mările cu tot ce cuprind ele. Tu dai viaţă tuturor acestor lucruri şi oştirea cerurilor se închină înaintea Ta. ( Neemia 9:6)",
"Te-ai pogorât pe Muntele Sinai, le-ai vorbit din înălţimea cerurilor şi le-ai dat porunci drepte, legi adevărate, învăţături şi orânduiri minunate. ( Neemia 9:13)",
"Dar Tu, Tu eşti un Dumnezeu gata să ierţi, îndurător şi milostiv, încet la mânie şi bogat în bunătate. Şi nu i-ai părăsit. ( Neemia 9:17 u. p.)","Tu ai fost drept în tot ce ni s-a întâmplat, căci Te-ai arătat credincios, iar noi am făcut rău. ( Neemia 9:33)",
 "Adu-Ţi aminte de mine, Dumnezeule, pentru aceste lucruri şi nu uita faptele mele evlavioase, făcute pentru Casa Dumnezeului meu şi pentru lucrurile care trebuie păzite în ea! ( Neemia 13:14)",'Atunci Haman a zis împăratului Ahaşveroş: "În toate ţinuturile împărăţiei tale este risipit un popor deosebit între popoare, care are legi deosebite de ale tuturor popoarelor şi nu ţine legile împăratului. Nu este în folosul împăratului să-l lase liniştit. (Estera 3:8)',
"Căci Iudeul Mardoheu era cel dintâi după împăratul Ahaşveroş. El era cu vază între Iudei şi iubit de mulţimea fraţilor săi, căci a căutat binele poporului său şi a vorbit pentru fericirea întregului său neam. (Estera 10:3)", "Ferice de omul pe care-l ceartă Dumnezeu! Nu nesocoti mustrarea Celui Atotputernic. (Iov 5:17)",
"El face rana şi tot El o leagă; El răneşte şi mâna Lui tămăduieşte. (Iov 5:18)",
"De şase ori te va izbăvi din necaz şi de şapte ori nu te va atinge răul. (Iov 5:19)",
"El te va scăpa de moarte în vreme de foamete şi de loviturile sabiei în vreme de război. (Iov 5:20)",
"Vei intra în mormânt la bătrâneţe, ca snopul strâns la vremea lui. (Iov 5:26)",
"Nu, Dumnezeu nu leapădă pe omul fără prihană şi nu ocroteşte pe cei răi. (Iov 8:20)",
"Ba încă, El îţi umple gura cu strigăte de bucurie, şi buzele cu cântări de veselie. (Iov 8:21)",
"El face lucruri mari şi nepătrunse, minuni fără număr. (Iov 9:10)",
"Mâinile Tale m-au făcut şi m-au zidit, ele m-au întocmit în întregime… Şi Tu să mă nimiceşti! (Iov 10:8)",
"Tu, îndreaptă-ţi inima spre Dumnezeu, întinde-ţi mâinile spre El. (Iov 11:13)",
"Depărtează-te de fărădelege şi nu lăsa nedreptatea să locuiască în cortul tău. (Iov 11:14)",
"Şi atunci, îţi vei ridica fruntea fără teamă, vei fi tare şi fără frică; îţi vei uita suferinţele, şi-ţi vei aduce aminte de ele ca de nişte ape care s-au scurs. (Iov 11:15,16)",
"Zilele tale vor străluci mai tare decât soarele la amiază, întunericul tău va fi ca lumina dimineţii. (Iov 11:17)",
"Vei fi plin de încredere, şi nădejdea nu-ţi va fi zadarnică. Te vei uita în jurul tău şi vei vedea că te poţi odihni liniştit. (Iov 11:18)",
"Cel fără prihană rămâne totuşi tare pe calea lui, cel cu mâinile curate se întăreşte tot mai mult. (Iov 17:9)","Dar ştiu că Răscumpărătorul meu este viu şi că Se va ridica la urmă pe pământ. (Iov 19:25)",
"Chiar dacă mi se va nimici pielea şi chiar dacă nu voi mai avea carne, voi vedea totuşi pe Dumnezeu. (Iov 19:26)",
"Îl voi vedea şi-mi va fi binevoitor; ochii mei Îl vor vedea, şi nu ai altuia.  Sufletul meu tânjeşte de dorul acesta înăuntrul meu. (Iov 19:27)",
"Dacă eşti fără prihană, are Cel Atotputernic vreun folos? Şi dacă trăieşti fără vină, ce va câştiga El? (Iov 22:3)",
"Împrietenește-te dar cu Dumnezeu și vei avea pace; te vei bucura astfel iarăși de fericire. (Iov 22:21)",
"Primeşte învăţătură din gura Lui şi pune-ţi la inimă cuvintele Lui. (Iov 22:22)",
"Vei fi aşezat iarăşi la locul tău, dacă te vei întoarce la Cel Atotputernic, dacă depărtezi fărădelegea din cortul tău. (Iov 22:23)",
"Îl vei ruga, şi te va asculta, şi îţi vei putea împlini juruinţele. (Iov 22:27)",
"Pe ce vei pune mâna îţi va izbuti, pe cărările tale va străluci lumina. (Iov 22:28)",
"Vină smerirea, tu te vei ruga pentru ridicarea ta: Dumnezeu ajută pe cel cu ochii plecaţi. (Iov 22:29)",
"Şi totuşi Dumnezeu, prin puterea Lui, lungeşte zilele celor silnici, şi iată-i în picioare când nu mai trăgeau nădejde de viaţă; El le dă linişte şi încredere, are privirile îndreptate spre căile lor. (Iov 24:22,23)",
"El întinde miazănoaptea asupra golului, şi spânzură pământul pe nimic. Leagă apele în norii Săi, şi norii nu se sparg sub greutatea lor. (Iov 26:7,8)",
"Suflarea Lui înseninează cerul, mâna Lui străpunge şarpele fugar. (Iov 26:13)",
"Şi acestea sunt doar marginile căilor Sale, şi numai adierea lor uşoară ajunge până la noi! Dar tunetul lucrărilor Lui puternice cine-l va auzi? (Iov 26:14)",
"Duhul lui Dumnezeu m-a făcut şi suflarea Celui Atotputernic îmi dă viaţă. (Iov 33:4)",
"Ascultaţi-mă dar, oameni pricepuţi! Departe de Dumnezeu nedreptatea, departe de Cel Atotputernic fărădelegea! (Iov 34:10)",
"El dă omului după faptele lui, răsplăteşte fiecăruia după căile lui (Iov 34:11)",
"Nu, negreşit, Dumnezeu nu săvârşeşte fărădelegea; Cel Atotputernic nu calcă dreptatea. (Iov 34:12)",
"Dacă nu s-ar gândi decât la El, dacă Şi-ar lua înapoi duhul şi suflarea, tot ce este carne ar pieri deodată şi omul s-ar întoarce în ţărână. (Iov 34:14, 15)",
"Căci Dumnezeu vede purtarea tuturor, priveşte paşii fiecăruia. (Iov 34:21)",
"Nu este nici întuneric, nici umbră a morţii unde să se poată ascunde cei ce fac fărădelegea. (Iov 34:22)",
"Dumnezeu n-are nevoie să privească multă vreme ca să tragă pe un om la judecată înaintea Lui. (Iov 34:23)",
"El zdrobeşte pe cei mari fără cercetare şi pune pe alţii în locul lor. (Iov 34:24)",
"Dacă dă El pace, cine poate s-o tulbure? Dacă Îşi ascunde El Faţa, cine poate să-L vadă? (Iov 34:29)",
"Măcar că zici că nu-L vezi, totuşi pricina ta este înaintea Lui: Aşteaptă-L! (Iov 35:14)",
"Dar, pentru că mânia Lui nu pedepseşte încă, nu înseamnă că puţin Îi pasă de nelegiuire. (Iov 35:15)",
"Dumnezeu este puternic, dar nu leapădă pe nimeni şi este puternic prin tăria priceperii Lui. (Iov 36:5)",
"El nu lasă pe cel rău să trăiască şi face dreptate celui nenorocit. (Iov 36:6)",
"Nu-Şi întoarce ochii de la cei fără prihană şi-i pune pe scaunul de domnie cu împăraţii, îi aşază pentru totdeauna ca să domnească. (Iov 36:7)",
"Îi înştiinţează ca să se îndrepte, îi îndeamnă să se întoarcă de la nelegiuire. Dacă ascultă şi se supun, îşi sfârşesc zilele în fericire şi anii în bucurie. (Iov:36: 10,11)",
"Dar Dumnezeu scapă pe cel nenorocit prin nenorocirea lui şi prin suferinţă îl înştiinţează. (Iov 36:15)",
"Şi pe tine te va scoate din strâmtorare, ca să te pună la loc larg, în slobozenie deplină, şi masa ta va fi încărcată cu bucate gustoase. (Iov 36:16)",
"Fereşte-te să faci rău, căci suferinţa te îndeamnă la rău. (Iov 36:21)",
"Dumnezeu este mare în puterea Lui; cine ar putea să înveţe pe alţii ca El? (Iov 36:22)",
"Nu uita să lauzi faptele Lui, pe care toţi oamenii trebuie să le mărească! (Iov 36:24)",
"Iată ce mare e Dumnezeu! Dar noi nu-L putem pricepe, numărul anilor Lui nimeni nu l-a pătruns. (Iov 36:26)",
"Căci El trage la El picăturile de apă, le preface în abur şi dă ploaia, pe care norii o strecoară şi o picură peste mulţimea oamenilor. (Iov 36:27,28)",
"Iată, El Îşi întinde lumina în jurul Lui şi acoperă adâncimile mării. (Iov 36:30)",
"Dă de veste că e de faţă printr-un bubuit şi până şi turmele Îi simt apropierea. (Iov 36:33)",
'Dumnezeu tună cu glasul Lui în chip minunat; face lucruri mari pe care noi nu le înţelegem. (Iov 37:5)',"Dumnezeu, prin suflarea Lui, face gheaţa şi micşorează locul apelor mari. (Iov 37:10)","Pe Cel Atotputernic nu-L putem ajunge, căci este mare în tărie, dar dreptul şi dreptatea deplină El nu le frânge. (Iov 37:23)","De aceea oamenii trebuie să se teamă de El; El nu-Şi îndreaptă privirile spre cei ce se cred înţelepţi. (Iov 37:24)",
"Ştiu că Tu poţi totul şi că nimic nu poate sta împotriva gândurilor Tale. (Iov 42:2)",
"Urechea mea auzise vorbindu-se de Tine, dar acum ochiul meu Te-a văzut. De aceea mi-e scârbă de mine şi mă pocăiesc în ţărână şi cenuşă. (Iov 42:5, 6)",
"Ferice de omul care nu se duce la sfatul celor răi, nu se opreşte pe calea celor păcătoşi şi nu se aşază pe scaunul celor batjocoritori! Ci îşi găseşte plăcerea în Legea Domnului, şi zi şi noapte cugetă la Legea Lui! (Psalmii 1:1,2)",
"El este ca un pom sădit lângă un izvor de apă, care îşi dă rodul la vremea lui şi ale cărui frunze nu se veştejesc: tot ce începe, duce la bun sfârşit. (Psalmii 1:3)",
"Nu tot aşa este cu cei răi: ci ei sunt ca pleava pe care o spulberă vântul. (Psalmii 1:4)",
"De aceea cei răi nu pot ţine capul sus în ziua judecăţii, nici păcătoşii în adunarea celor neprihăniţi. (Psalmii 1:5)",
"Căci Domnul cunoaşte calea celor neprihăniţi, dar calea păcătoşilor duce la pieire. (Psalmii 1:6)",
'"Eu voi vesti hotărârea Lui" - zice Unsul - "Domnul Mi-a zis: "Tu eşti Fiul Meu! Astăzi Te-am născut. (Psalmii 2:7)',"Cere-Mi, şi-Ţi voi da neamurile de moştenire, şi marginile pământului în stăpânire! (Psalmii 2:8)","Tu le vei zdrobi cu un toiag de fier şi le vei sfărâma ca pe vasul unui olar. (Psalmii 2:9)","Slujiţi Domnului cu frică şi bucuraţi-vă, tremurând. (Psalmii 2:11)","Daţi cinste Fiului, ca să nu Se mânie, şi să nu pieriţi pe calea voastră, căci mânia Lui este gata să se aprindă! Ferice de toţi câţi se încred în El! (Psalmii 2:12)",
"Eu strig cu glasul meu către Domnul, şi El îmi răspunde din muntele Lui cel sfânt. (Psalmii 3:4)",
"La Domnul este scăparea: binecuvântarea Ta să fie peste poporul Tău. (Psalmii 3:8)",
"Să ştiţi că Domnul Şi-a ales un om pe care-l iubeşte: Domnul aude când strig către El. (Psalmii 4:3)",
"Eu mă culc şi adorm în pace, căci numai Tu, Doamne, îmi dai linişte deplină în locuinţa mea. (Psalmii 4:8)",
"Atunci toţi cei ce se încred în Tine se vor bucura, se vor înveseli totdeauna, căci Tu îi vei ocroti. Tu vei fi bucuria celor ce iubesc Numele Tău. (Psalmii 5:11)",
"Căci Tu binecuvântezi pe cel neprihănit, Doamne, şi-l înconjori cu bunăvoinţa Ta, cum l-ai înconjura cu un scut. (Psalmii 5:12)",
"Domnul îmi ascultă cererile şi Domnul îmi primeşte rugăciunea! (Psalmii 6:9)",
"Fărădelegea pe care a urzit-o se întoarce asupra capului lui, şi silnicia pe care a făcut-o se coboară înapoi pe ţeasta capului lui. (Psalmii 7:16)",
"I-ai dat stăpânire peste lucrurile mâinilor Tale, toate le-ai pus sub picioarele lui: oile şi boii laolaltă, fiarele câmpului, păsările cerului şi peştii mării, tot ce străbate cărările mărilor. Doamne Dumnezeul nostru, cât de minunat este Numele Tău pe tot pământul! (Psalmii 8:6-9)",
"Cei ce cunosc Numele Tău se încred în Tine, căci Tu nu părăseşti pe cei ce Te caută, Doamne! (Psalmii 9:10)",
"Căci El răzbună sângele vărsat şi Îşi aduce aminte de cei nenorociţi, nu uită strigătele lor. (Psalmii 9:12)",
"Căci cel nenorocit nu este uitat pe vecie, nădejdea celor sărmani nu piere pe vecie. (Psalmii 9:18)",
"Domnul este în templul Lui cel sfânt, Domnul Îşi are scaunul de domnie în ceruri. Ochii Lui privesc, şi pleoapele Lui cercetează pe fiii oamenilor. (Psalmii 11:4)",
"Căci Domnul este drept, iubeşte dreptatea, şi cei neprihăniţi privesc faţa Lui. (Psalmii 11:7)",
'"Pentru că cei nenorociţi sunt asupriţi şi pentru că săracii gem, acum", zice Domnul, "Mă scol şi aduc mântuire celor obijduiţi." (Psalmii 12:5)',
"Tu, Doamne, îi vei păzi şi-i vei apăra de neamul acesta pe vecie. (Psalmii 12:7)",
"Ei vor tremura de spaimă, când Se va arăta Dumnezeu în mijlocul neamului neprihănit. (Psalmii 14:5)",
"El priveşte cu dispreţ pe cel vrednic de dispreţuit, dar cinsteşte pe cei ce se tem de Domnul. El nu-şi ia vorba înapoi dacă face un jurământ în paguba lui. (Psalmii 15:4)",
"El nu-şi dă banii cu dobândă şi nu ia mită împotriva celui nevinovat. Cel ce se poartă aşa, nu se clatină niciodată. (Psalmii 15:5)",
"Sfinţii care sunt în ţară, oamenii evlavioşi, sunt toată plăcerea mea. (Psalmii 16:3)",
"Am necurmat pe Domnul înaintea ochilor mei: când este El la dreapta mea, nu mă clatin. (Psalmii 16:8)",
"Îmi vei arăta cărarea vieţii; înaintea feţei Tale sunt bucurii nespuse şi desfătări veşnice în dreapta Ta. (Psalmii 16:11)",
"Dar eu, în nevinovăţia mea, voi vedea faţa Ta: cum mă voi trezi, mă voi sătura de chipul Tău. (Psalmii 17:15)",
"Dar, în strâmtorarea mea, am chemat pe Domnul şi am strigat către Dumnezeul meu: din locaşul Lui, El mi-a auzit glasul, şi strigătul meu a ajuns până la El, până la urechile Lui. (Psalmii 18:6)",
"El Şi-a întins mâna de sus, m-a apucat, m-a scos din apele cele mari; m-a izbăvit de potrivnicul meu cel puternic, de vrăjmaşii mei, care erau mai tari decât mine. (Psalmii 18:16,17)",
"El m-a scos la loc larg şi m-a scăpat, pentru că mă iubeşte. (Psalmii 18:19)",
"Cerurile spun slava lui Dumnezeu, şi întinderea lor vesteşte lucrarea mâinilor Lui. O zi istoriseşte alteia acest lucru, o noapte dă de ştire alteia despre el. (Psalmii 19:1,2)",
"Orânduirile Domnului sunt fără prihană şi înveselesc inima; poruncile Domnului sunt curate şi luminează ochii. (Psalmii 19:8)",
"Frica de Domnul este curată şi ţine pe vecie; judecăţile Domnului sunt adevărate, toate sunt drepte. (Psalmii 19:9)",
"Primeşte cu bunăvoinţă cuvintele gurii mele şi cugetele inimii mele, Doamne, Stânca mea şi Izbăvitorul meu! (Psalmii 19:14)",
"Să te asculte Domnul în ziua necazului, să te ocrotească Numele Dumnezeului lui Iacov, să-ţi trimită ajutor din locaşul Său cel sfânt şi să te sprijine din Sion! (Psalmii 20:1,2)",
"Să-ţi dea ce-ţi doreşte inima şi să-ţi împlinească toate planurile tale! (Psalmii 20:4)",
"Atunci noi ne vom bucura de biruinţa ta şi vom flutura steagul în Numele Dumnezeului nostru. Domnul să-ţi asculte toate dorinţele tale! (Psalmii 20:5)",
"Ştiu de acum că Domnul scapă pe unsul Său şi-i va răspunde din ceruri, din locaşul Lui cel sfânt, prin ajutorul atotputernic al dreptei Lui. (Psalmii 20:6)",
"Căci i-ai ieşit înainte cu binecuvântări de fericire şi i-ai pus pe cap o cunună de aur curat. (Psalmii 21:3)",
"Îţi cerea viaţa, şi i-ai dat-o: o viaţă lungă pentru totdeauna şi pe vecie. (Psalmii 21:4)",
"Domnul este păstorul meu: nu voi duce lipsă de nimic. (Psalmii 23:1)",
"El mă paşte în păşuni verzi şi mă duce la ape de odihnă; îmi înviorează sufletul şi mă povăţuieşte pe cărări drepte, din pricina Numelui Său. (Psalmii 23:2,3)",
"Chiar dacă ar fi să umblu prin valea umbrei morţii, nu mă tem de niciun rău, căci Tu eşti cu mine. Toiagul şi nuiaua Ta mă mângâie. (Psalmii 23:4)",
"Tu îmi întinzi masa în faţa potrivnicilor mei; îmi ungi capul cu untdelemn, şi paharul meu este plin de dă peste el. (Psalmii 23:5)",
"Da, fericirea şi îndurarea mă vor însoţi în toate zilele vieţii mele, şi voi locui în Casa Domnului până la sfârşitul zilelor mele. (Psalmii 23:6)",
"Al Domnului este pământul cu tot ce este pe el, lumea şi cei ce o locuiesc! Căci El l-a întemeiat pe mări şi l-a întărit pe râuri. (Psalmii 24:1,2)",
"Acela va căpăta binecuvântarea Domnului, starea după voia Lui dată de Dumnezeul mântuirii lui. (Psalmii 24:5)",
"Porţi, ridicaţi-vă capetele; ridicaţi-vă, porţi veşnice, ca să intre Împăratul slavei! - (Psalmii 24:7)",
"Da, toţi cei ce nădăjduiesc în Tine nu vor fi daţi de ruşine: ci de ruşine vor fi daţi cei ce Te părăsesc fără temei. (Psalmii 25:3)",
"El face pe cei smeriţi să umble în tot ce este drept. El învaţă pe cei smeriţi calea Sa. (Psalmii 25:9)",
"Toate cărările Domnului sunt îndurare şi credincioşie pentru cei ce păzesc legământul şi poruncile Lui. (Psalmii 25:10)",
"Cine este omul care se teme de Domnul? Aceluia Domnul îi arată calea pe care trebuie s-o aleagă. (Psalmii 25:12)",
"Prietenia Domnului este pentru cei ce se tem de El, şi legământul făcut cu El le dă învăţătură. (Psalmii 25:14)",
"Eu îmi întorc necurmat ochii spre Domnul, căci El îmi va scoate picioarele din laţ. (Psalmii 25:15)",
"Să mă ocrotească nevinovăţia şi neprihănirea, când îmi pun nădejdea în Tine! (Psalmii 25:21)",
"Domnul este lumina şi mântuirea mea: de cine să mă tem? Domnul este sprijinitorul vieţii mele: de cine să-mi fie frică? (Psalmii 27:1)",
"Căci El mă va ocroti în coliba Lui, în ziua necazului, mă va ascunde sub acoperişul cortului Lui şi mă va înălţa pe o stâncă. (Psalmii 27:5)",
"Căci tatăl meu şi mama mea mă părăsesc, dar Domnul mă primeşte. (Psalmii 27:10)",
"Domnul este tăria mea și scutul meu; în El mi se încrede inima, și sunt ajutat. De aceea îmi este plină de veselie inima și-L laud prin cântările mele. (Psalmii 28:7)",
"Domnul este tăria poporului Său, El este stânca izbăvitoare a unsului Său. (Psalmii 28:8)",
"Glasul Domnului este puternic, glasul Domnului este măreţ. (Psalmii 29:4)",
"Domnul stătea pe scaunul Lui de domnie când cu potopul, şi Domnul împărăţeşte în veci pe scaunul Lui de domnie. (Psalmii 29:10)",
"Domnul dă tărie poporului Său, Domnul binecuvântă pe poporul Său cu pace. (Psalmii 29:11)",
"Doamne Dumnezeule, eu am strigat către Tine, şi Tu m-ai vindecat. (Psalmii 30:2)",
"Căci mânia Lui ţine numai o clipă, dar îndurarea Lui ţine toată viaţa: seara vine plânsul, iar dimineaţa, veselia. (Psalmii 30:5)",
"O, cât de mare este bunătatea Ta, pe care o păstrezi pentru cei ce se tem de Tine şi pe care o arăţi celor ce se încred în Tine, în faţa fiilor oamenilor! (Psalmii 31:19)",
"Iubiţi, dar, pe Domnul, toţi cei iubiţi de El. Căci Domnul păzeşte pe cei credincioşi, şi pedepseşte aspru pe cei mândri. (Psalmii 31:23)",
"Ferice de cel cu fărădelegea iertată şi de cel cu păcatul acoperit! (Psalmii 32:1)",
"Ferice de omul căruia nu-i ţine în seamă Domnul nelegiuirea şi în duhul căruia nu este viclenie! (Psalmii 32:2)",
"Tu eşti ocrotirea mea, Tu mă scoţi din necaz, Tu mă înconjori cu cântări de izbăvire.  (Psalmii 32:7)",
"„Eu - zice Domnul - te voi învăţa şi-ţi voi arăta calea pe care trebuie s-o urmezi, te voi sfătui şi voi avea privirea îndreptată asupra ta.” (Psalmii 32:8)",
"Căci cuvântul Domnului este adevărat, şi toate lucrările Lui se împlinesc cu credincioşie. (Psalmii 33:4)",
"Cerurile au fost făcute prin cuvântul Domnului, şi toată oştirea lor prin suflarea gurii Lui. (Psalmii 33:6)",
"Căci El zice şi se face; porunceşte, şi ce porunceşte ia fiinţă. (Psalmii 33:9)",
"Dar sfaturile Domnului dăinuie pe vecie, şi planurile inimii Lui, din neam în neam. (Psalmii 33:11)",
"Ferice de poporul al cărui Dumnezeu este Domnul! Ferice de poporul pe care Şi-l alege El de moştenire! (Psalmii 33:12)",
"Când îţi întorci privirile spre El, te luminezi de bucurie, şi nu ţi se umple faţa de ruşine. (Psalmii 34:5)",
"Când strigă un nenorocit, Domnul aude şi-l scapă din toate necazurile lui. (Psalmii 34:6)",
"Îngerul Domnului tăbărăşte în jurul celor ce se tem de El şi-i scapă din primejdie. (Psalmii 34:7)",
"Gustaţi şi vedeţi ce bun este Domnul! Ferice de omul care se încrede în El! (Psalmii 34:8)",
"Temeţi-vă de Domnul, voi, sfinţii Lui, căci de nimic nu duc lipsă cei ce se tem de El! (Psalmii 34:9)",
"Puii de leu duc lipsă și li-e foame, dar cei ce caută pe Domnul nu duc lipsă de niciun bine. (Psalmii 34:10)",
"Ochii Domnului sunt peste cei fără prihană, şi urechile Lui iau aminte la strigătele lor. (Psalmii 34:15)",
"Când strigă cei fără prihană, Domnul aude şi-i scapă din toate necazurile lor. (Psalmii 34:17)",
"Domnul este aproape de cei cu inima înfrântă şi mântuieşte pe cei cu duhul zdrobit. (Psalmii 34:18)",
"De multe ori vine nenorocirea peste cel fără prihană, dar Domnul îl scapă întotdeauna din ea. (Psalmii 34:19)",
"Domnul scapă sufletul robilor Săi, şi niciunul din cei ce se încred în El, nu este osândit. (Psalmii 34:22)",
"Şi atunci mi se va bucura sufletul în Domnul: se va înveseli de mântuirea Lui. (Psalmii 35:9)",
"Se satură de belşugul Casei Tale, şi-i adăpi din şuvoiul desfătărilor Tale. (Psalmii 36:8)",
"Căci la Tine este izvorul vieţii; prin lumina Ta vedem lumina. (Psalmii 36:9)",
"Nu te mânia pe cei răi şi nu te uita cu jind la cei ce fac răul; căci sunt cosiţi iute ca iarba şi se veştejesc ca verdeaţa. (Psalmii 37:1-2)",
"Încrede-te în Domnul şi fă binele; locuieşte în ţară şi umblă în credincioşie. (Psalmii 37:3)",
"Domnul să-ţi fie desfătarea, şi El îţi va da tot ce-ţi doreşte inima. (Psalmii 37:4)",
"Încredinţează-ţi soarta în mâna Domnului, încrede-te în El, şi El va lucra, El va face să strălucească dreptatea ta ca lumina, şi dreptul tău ca soarele la amiază. (Psalmii 37:5,6)",
"Taci înaintea Domnului şi nădăjduieşte în El. Nu te mânia pe cel ce izbuteşte în umbletele lui, pe omul care îşi vede împlinirea planurilor lui rele. (Psalmii 37:7)",
"Lasă mânia, părăseşte iuţimea; nu te supăra, căci supărarea duce numai la rău. (Psalmii 37:8)",
"Fiindcă cei răi vor fi nimiciţi, iar cei ce nădăjduiesc în Domnul vor stăpâni ţara. (Psalmii 37:9)",
"Încă puţină vreme, şi cel rău nu va mai fi; te vei uita la locul unde era, şi nu va mai fi. (Psalmii 37:10)",
"Cei blânzi moştenesc ţara şi au belşug de pace. (Psalmii 37:11)",
"Cel rău face la planuri împotriva celui neprihănit şi scrâşneşte din dinţi împotriva lui. (Psalmii 37:12)",
"Domnul râde de cel rău, căci vede că-i vine şi lui ziua. (Psalmii 37:13)",
"Cei răi trag sabia şi îşi încordează arcul, ca să doboare pe cel nenorocit şi sărac, ca să înjunghie pe cei cu inima neprihănită. (Psalmii 37:14)",
"Dar sabia lor intră în însăşi inima lor, şi li se sfărâmă arcurile. (Psalmii 37:15)",
"Mai mult face puţinul celui neprihănit decât belşugul multor răi. (Psalmii 37:16)",
"Căci braţele celui rău vor fi zdrobite, dar Domnul sprijină pe cei neprihăniţi. (Psalmii 37:17)",
"Domnul cunoaşte zilele oamenilor cinstiţi; şi moştenirea lor ţine pe vecie. (Psalmii 37:18)",
"Ei nu rămân de ruşine în ziua nenorocirii, ci au de ajuns în zilele de foamete. (Psalmii 37:19)",
"Dar cei răi pier, şi vrăjmaşii Domnului sunt ca cele mai frumoase păşuni: pier, pier ca fumul. (Psalmii 37:20)",
"Cel rău ia cu împrumut, şi nu dă înapoi; dar cel neprihănit este milos şi dă. (Psalmii 37:21)",
"Căci cei binecuvântaţi de Domnul stăpânesc ţara, dar cei blestemaţi de El sunt nimiciţi. (Psalmii 37:22)",
"Domnul întăreşte paşii omului, când Îi place calea lui; dacă se întâmplă să cadă, nu este doborât de tot, căci Domnul îl apucă de mână. (Psalmii 37:23,24)",
"Am fost tânăr, şi am îmbătrânit, dar n-am văzut pe cel neprihănit părăsit, nici pe urmaşii lui cerşindu-şi pâinea. Ci el întotdeauna este milos şi dă cu împrumut; şi urmaşii lui sunt binecuvântaţi. (Psalmii 37:25,26)",
"Depărtează-te de rău, fă binele, şi vei dăinui pe vecie. Căci Domnul iubeşte dreptatea şi nu părăseşte pe credincioşii Lui. Totdeauna ei sunt sub paza Lui, dar sămânţa celor răi este nimicită. (Psalmii 37:27,28)",
"Cei neprihăniţi vor stăpâni ţara şi vor locui în ea pe vecie. (Psalmii 37:29)",
"Gura celui neprihănit vesteşte înţelepciunea, şi limba lui trâmbiţează dreptatea. (Psalmii 37:30)",
"Legea Dumnezeului său este în inima lui; şi nu i se clatină paşii. (Psalmii 37:31)",
"Cel rău pândeşte pe cel neprihănit şi caută să-l omoare. Dar Domnul nu-l lasă în mâinile lui şi nu-l osândeşte când vine la judecată. (Psalmii 37:32,33)",
"Nădăjduieşte în Domnul, păzeşte calea Lui, şi El te va înălţa ca să stăpâneşti ţara: vei vedea pe cei răi nimiciţi. (Psalmii 37:34)",
"Am văzut pe cel rău în toată puterea lui; se întindea ca un copac verde. Dar, când am trecut a doua oară, nu mai era acolo; l-am căutat, dar nu l-am mai putut găsi. (Psalmii 37:35,36)",
"Uită-te bine la cel fără prihană şi priveşte pe cel fără vicleşug; căci omul de pace are parte de moştenitori. (Psalmii 37:37)",
"Dar cei răzvrătiţi sunt nimiciţi cu toţii, sămânţa celor răi este prăpădită. (Psalmii 37:38)",
"Scăparea celor neprihăniţi vine de la Domnul; El este ocrotitorul lor la vremea necazului. (Psalmii 37:39)",
"Domnul îi ajută şi-i izbăveşte; îi izbăveşte de cei răi şi-i scapă, pentru că se încred în El. (Psalmii 37:40)",
"Îmi pusesem nădejdea în Domnul, şi El S-a plecat spre mine, mi-a ascultat strigătele. (Psalmii 40:1)",
"Doamne Dumnezeule, multe sunt minunile şi planurile Tale pentru mine: nimeni nu se poate asemăna cu Tine. Aş vrea să le vestesc şi să le trâmbiţez, dar numărul lor este prea mare, ca să le povestesc. (Psalmii 40:5)",
"Eu sunt sărac şi lipsit, dar Domnul Se gândeşte la mine. Tu eşti ajutorul şi izbăvitorul meu: nu zăbovi, Dumnezeule! (Psalmii 40:17)",
"Ferice de cel ce îngrijeşte de cel sărac! Căci în ziua nenorocirii Domnul îl izbăveşte; (Psalmii 41:1)",
"Prin aceasta voi cunoaşte că mă iubeşti, dacă nu mă va birui vrăjmaşul meu. (Psalmii 41:11)",
"Ziua, Domnul îmi dădea îndurarea Lui, iar noaptea, cântam laudele Lui şi înălţam o rugăciune Dumnezeului vieţii mele. (Psalmii 42:8)",
"Trimite lumina şi credincioşia Ta, ca să mă călăuzească şi să mă ducă la muntele Tău cel sfânt şi la locaşurile Tale! (Psalmii 43:3)",
"Tu iubeşti neprihănirea şi urăşti răutatea. De aceea, Dumnezeule, Dumnezeul Tău Te-a uns cu un untdelemn de bucurie, mai presus decât pe tovarăşii Tăi de slujbă. (Psalmii 45:7)",
"Copiii tăi vor lua locul părinţilor tăi; îi vei pune domni în toată ţara. (Psalmii 45:16)",
"Dumnezeu este adăpostul şi sprijinul nostru, un ajutor care nu lipseşte niciodată în nevoi. (Psalmii 46:1)",
"Dumnezeu este în mijlocul ei: ea nu se clatină; Dumnezeu o ajută în revărsatul zorilor. (Psalmii 46:5)",
"Domnul oştirilor este cu noi, Dumnezeul lui Iacov este un turn de scăpare pentru noi. - (Psalmii 46:7)",
"„Opriţi-vă şi să ştiţi că Eu sunt Dumnezeu: Eu stăpânesc peste neamuri, Eu stăpânesc pe pământ.” - (Psalmii 46:10)",
"El ne supune popoarele, El pune neamurile sub picioarele noastre. (Psalmii 47:3)",
"Dumnezeu împărăţeşte peste neamuri, Dumnezeu şade pe scaunul Lui de domnie cel sfânt. (Psalmii 47:8)",
"Domnitorii popoarelor se adună împreună cu poporul Dumnezeului lui Avraam; căci ale lui Dumnezeu sunt scuturile pământului: El este mai înalt şi mai presus de orice. (Psalmii 47:9)",
"Iată, Dumnezeul acesta este Dumnezeul nostru în veci de veci; El va fi călăuza noastră până la moarte. (Psalmii 48:14)",
"Dar mie, Dumnezeu îmi va scăpa sufletul din Locuinţa morţilor, căci mă va lua sub ocrotirea Lui. - (Psalmii 49:15)",
"Cheamă-Mă în ziua necazului, şi Eu te voi izbăvi, iar tu Mă vei proslăvi! (Psalmii 50:15)",
"Luaţi seama, dar, voi care uitaţi pe Dumnezeu, ca nu cumva să vă sfâşii, şi să nu fie nimeni să vă scape. (Psalmii 50:22)",
"Cine aduce mulţumiri ca jertfă, acela Mă proslăveşte, şi celui ce veghează asupra căii lui, aceluia îi voi arăta mântuirea lui Dumnezeu. (Psalmii 50:23)",
"Jertfele plăcute lui Dumnezeu sunt un duh zdrobit: Dumnezeule, Tu nu dispreţuieşti o inimă zdrobită şi mâhnită. (Psalmii 51:17)",
"Pentru ce te făleşti cu răutatea ta, asupritorule? Bunătatea lui Dumnezeu ţine în veci. (Psalmii 52:1)",
"Te voi lăuda totdeauna, pentru că ai lucrat; şi, în faţa copiilor Tăi, voi nădăjdui în Numele Tău, căci este binevoitor. (Psalmii 52:9)",
"O! cine va face să pornească din Sion izbăvirea lui Israel? Când va aduce Dumnezeu înapoi pe prinşii de război ai poporului Său, Iacov se va înveseli, şi Israel se va bucura. (Psalmii 53:6)",
"Încredinţează-ţi soarta în mâna Domnului, şi El te va sprijini. El nu va lăsa niciodată să se clatine cel neprihănit. (Psalmii 55:22)",
"Ori de câte ori mă tem, eu mă încred în Tine. (Psalmii 56:3)",
"Tu numeri paşii vieţii mele de pribeag; pune-mi lacrimile în burduful Tău: nu sunt ele scrise în cartea Ta? (Psalmii 56:8)",
"Căci mi-ai izbăvit sufletul de la moarte, mi-ai ferit picioarele de cădere, ca să umblu înaintea lui Dumnezeu, în lumina celor vii. (Psalmii 56:13)",
"Căci bunătatea Ta ajunge până la ceruri, şi credincioşia Ta până la nori. (Psalmii 57:10)",
"Să piară ca un melc care se topeşte umblând; să nu vadă soarele, ca stârpitura unei femei! (Psalmii 58:8)",
"Dumnezeul meu, în bunătatea Lui, îmi iese înainte; Dumnezeu mă face să-mi văd împlinită dorinţa faţă de cei ce mă prigonesc. (Psalmii 59:10)",
"Ai dat celor ce se tem de Tine un steag, ca să-l înalţe spre biruinţa adevărului. - (Psalmii 60:4)",
"Căci Tu, Dumnezeule, îmi asculţi juruinţele, Tu îmi dai moştenirea celor ce se tem de Numele Tău. (Psalmii 61:5)",
'O dată a vorbit Dumnezeu, de două ori am auzit că: "Puterea este a lui Dumnezeu." (Psalmii 62:11)',
"A Ta, Doamne, este şi bunătatea, căci Tu răsplăteşti fiecăruia după faptele lui. (Psalmii 62:12)",
"Sufletul meu este lipit de Tine; dreapta Ta mă sprijină. (Psalmii 63:8)",
"Încununezi anul cu bunătăţile Tale, şi paşii Tăi varsă belşugul. (Psalmii 65:11)",
"Dumnezeu este pentru noi Dumnezeul izbăvirilor, şi Domnul Dumnezeu ne poate scăpa de moarte. (Psalmii 68:20)",
"Dumnezeul tău te-a făcut puternic. Întăreşte, Dumnezeule, ce ai făcut pentru noi în Templul Tău. (Psalmii 68:28)",
"Căci Domnul ascultă pe cei săraci şi nu nesocoteşte pe prinşii Lui de război. (Psalmii 69:33)",
" Da, bun este Dumnezeu cu Israel, cu cei cu inima curată. (Psalmii 73:1)",
"Ci Dumnezeu este Cel ce judecă: El coboară pe unul, şi înalţă pe altul. (Psalmii 75:7)",
"Eu sunt Domnul Dumnezeul tău care te-am scos din ţara Egiptului; deschide-ţi gura larg, şi ţi-o voi umple! (Psalmii 81:10)",
"Ferice de cei ce locuiesc în Casa Ta! Căci ei tot mai pot să Te laude. - (Psalmii 84:4)",
"Ferice de cei ce-şi pun tăria în Tine, în a căror inimă locuieşte încrederea. (Psalmii 84:5)",
"Tu, care eşti scutul nostru, vezi, Dumnezeule, şi priveşte faţa unsului Tău! (Psalmii 84:9)",
"Căci mai mult face o zi în curţile Tale decât o mie în altă parte; eu vreau mai bine să stau în pragul Casei Dumnezeului meu, decât să locuiesc în corturile răutăţii! (Psalmii 84:10)",
"Căci Domnul Dumnezeu este un soare şi un scut, Domnul dă îndurare şi slavă, şi nu lipseşte de niciun bine pe cei ce duc o viaţă fără prihană. (Psalmii 84:11)",
"Credincioşia şi bunătatea Mea vor fi cu el, şi tăria lui se va înălţa prin Numele Meu. (Psalmii 89:24)",
"Îi voi face veşnică sămânţa, şi scaunul lui de domnie, ca zilele cerurilor. (Psalmii 89:29)",
"nu-Mi voi călca legământul şi nu voi schimba ce a ieşit de pe buzele Mele. (Psalmii 89:34)",
"Cel ce stă sub ocrotirea Celui Preaînalt şi se odihneşte la umbra Celui atotputernic, zice despre Domnul: „El este locul meu de scăpare şi cetăţuia mea, Dumnezeul meu în care mă încred!” (Psalmii 91:1,2)",
"El te va acoperi cu penele Lui şi te vei ascunde sub aripile Lui. Căci scut şi pavăză este credincioşia Lui! (Psalmii 91:4)",
"O mie să cadă alături de tine, şi zece mii la dreapta ta, dar de tine nu se va apropia. (Psalmii 91:7)",
'Pentru că zici: "Domnul este locul meu de adăpost!" şi faci din Cel Preaînalt turnul tău de scăpare, de aceea nicio nenorocire nu te va ajunge, nicio urgie nu se va apropia de cortul tău. (Psalmii 91:9,10)',
"Căci El va porunci îngerilor Săi să te păzească în toate căile tale; şi ei te vor duce pe mâini, ca nu cumva să-ţi loveşti piciorul de vreo piatră. (Psalmii 91:11,12)",
"Fiindcă Mă iubeşte - zice Domnul - de aceea îl voi izbăvi; îl voi ocroti, căci cunoaşte Numele Meu. (Psalmii 91:14)",
"Când Mă va chema, îi voi răspunde; voi fi cu el în strâmtorare, îl voi izbăvi şi-l voi proslăvi. (Psalmii 91:15)",
"Îl voi sătura cu viaţă lungă şi-i voi arăta mântuirea Mea. (Psalmii 91:16)",
"Cel fără prihană înverzeşte ca finicul şi creşte ca cedrul din Liban. (Psalmii 92:12)",
"Ei aduc roade şi la bătrâneţe, sunt plini de suc şi verzi, ca să arate că Domnul este drept, El, Stânca mea, în care nu este nelegiuire. (Psalmii 92:14,15)",
"Când gânduri negre se frământă cu grămada înăuntrul meu, mângâierile Tale îmi înviorează sufletul. (Psalmii 94:19)",
"Dar Domnul este turnul meu de scăpare, Dumnezeul meu este stânca mea de adăpost. (Psalmii 94:22)",
"Căci El este Dumnezeul nostru, şi noi suntem poporul păşunii Lui, turma pe care o povăţuieşte mâna Lui… O! de aţi asculta azi glasul Lui! - (Psalmii 95:7)",
"Cântaţi Domnului, binecuvântaţi Numele Lui, vestiţi din zi în zi mântuirea Lui! (Psalmii 96:2)",
"Strălucirea şi măreţia sunt înaintea feţei Lui, slava şi podoaba sunt în Locaşul Lui cel Sfânt. (Psalmii 96:6)",
"Urâţi răul, cei ce iubiţi pe Domnul! El păzeşte sufletele credincioşilor Lui şi-i izbăveşte din mâna celor răi. (Psalmii 97:10)",
"Lumina este semănată pentru cel neprihănit, şi bucuria, pentru cei cu inima curată. (Psalmii 97:11)",
"El ia aminte la rugăciunea nevoiaşului şi nu-i nesocoteşte rugăciunea. (Psalmii 102:17)",
"Binecuvântă, suflete, pe Domnul şi nu uita niciuna din binefacerile Lui! El îţi iartă toate fărădelegile tale, El îţi vindecă toate bolile tale; El îţi izbăveşte viaţa din groapă, El te încununează cu bunătate şi îndurare. (Psalmii 103:2-4)",
"El îţi satură de bunătăţi bătrâneţea şi te face să întinereşti iarăşi ca vulturul. (Psalmii 103:5)",
"Domnul face dreptate şi judecată tuturor celor asupriţi. (Psalmii 103:6)",
"El nu Se ceartă fără încetare şi nu ţine mânia pe vecie. (Psalmii 103:9)",
"Ci cât sunt de sus cerurile faţă de pământ, atât este de mare bunătatea Lui pentru cei ce se tem de El; (Psalmii 103:11)",
"cât este de departe răsăritul de apus, atât de mult depărtează El fărădelegile noastre de la noi. (Psalmii 103:12)",
"Cum se îndură un tată de copiii lui, aşa Se îndură Domnul de cei ce se tem de El. (Psalmii 103:13)",
"Dar bunătatea Domnului ţine în veci pentru cei ce se tem de El, şi îndurarea Lui pentru copiii copiilor lor, pentru cei ce păzesc legământul Lui şi îşi aduc aminte de poruncile Lui, ca să le împlinească. (Psalmii 103:17,18)",
"Ferice de cei ce păzesc Legea, de cei ce înfăptuiesc dreptatea în orice vreme! (Psalmii 106:3)",
"a trimis cuvântul Său şi i-a tămăduit şi i-a scăpat de groapă. (Psalmii 107:20)",
"El a dat hrană celor ce se tem de El; El Îşi aduce pururi aminte de legământul Lui. (Psalmii 111:5)",
"Lucrările mâinilor Lui sunt credincioşie şi dreptate; toate poruncile Lui sunt adevărate, întărite pentru veşnicie, făcute cu credincioşie şi neprihănire. (Psalmii 111:7,8)",
"Sămânţa lui va fi puternică pe pământ; neamul oamenilor fără prihană va fi binecuvântat. (Psalmii 112:2)",
"El nu se teme de veşti rele, ci inima lui este tare, încrezătoare în Domnul. (Psalmii 112:7)",
"Domnul Şi-aduce aminte de noi: El va binecuvânta, va binecuvânta casa lui Israel, va binecuvânta casa lui Aaron, va binecuvânta pe cei ce se tem de Domnul, pe cei mici şi pe cei mari. (Psalmii 115:12,13)",
"Domnul să vă înmulţească tot mai mult, pe voi şi pe copiii voştri! (Psalmii 115:14)",
"Strigăte de biruinţă şi de mântuire se înalţă în corturile celor neprihăniţi: dreapta Domnului câştigă biruinţa! (Psalmii 118:15)",
"Dreapta Domnului se înalţă; dreapta Domnului câştigă biruinţa! (Psalmii 118:16)",
"Atunci nu voi roşi de ruşine la vederea tuturor poruncilor Tale! (Psalmii 119:6)",
"Cum îşi va ţine tânărul curată cărarea? Îndreptându-se după cuvântul Tău. (Psalmii 119:9)",
"Strâng cuvântul Tău în inima mea, ca să nu păcătuiesc împotriva Ta! (Psalmii 119:11)",
"Până ce am fost smerit, rătăceam; dar acum păzesc cuvântul Tău. (Psalmii 119:67)",
"Mai mult prețuiește pentru mine legea gurii Tale, decât o mie de lucruri de aur și de argint. (Psalmii 119:72)",
"Mâinile Tale m-au făcut și m-au întocmit; dă-mi pricepere, ca să învăț poruncile Tale! (Psalmii 119:73)",
"Cei ce se tem de Tine mă văd și se bucură, căci nădăjduiesc în făgăduințele Tale. (Psalmii 119:74)",
"Știu, Doamne, că judecățile Tale sunt drepte: din credincioșie m-ai smerit. (Psalmii 119:75)",
"Fă ca bunătatea Ta să-mi fie mângâierea, cum ai făgăduit robului Tău! (Psalmii 119:76)",
"Cuvântul Tău este o candelă pentru picioarele mele și o lumină pe cărarea mea. (Psalmii 119:105)",
"Este vremea ca Domnul să lucreze: căci ei calcă Legea Ta. (Psalmii 119:126)",
"Descoperirea cuvintelor Tale dă lumină, dă pricepere celor fără răutate. (Psalmii 119:130)",
"O iau înaintea străjilor de noapte şi deschid ochii, ca să mă gândesc adânc la cuvântul Tău. (Psalmii 119:148)",
"Temelia cuvântului Tău este adevărul, şi toate legile Tale cele drepte sunt veşnice. (Psalmii 119:160)",
"Multă pace au cei ce iubesc Legea Ta şi nu li se întâmplă nicio nenorocire. (Psalmii 119:165)",
"Îmi ridic ochii spre munţi… De unde-mi va veni ajutorul? Ajutorul îmi vine de la Domnul, care a făcut cerurile şi pământul. (Psalmii 121:1,2)",
"Da, El nu va îngădui să ţi se clatine piciorul; Cel ce te păzeşte nu va dormita. Iată că nu dormitează, nici nu doarme Cel ce păzeşte pe Israel. (Psalmii 121:3,4)",
"Domnul este păzitorul tău, Domnul este umbra ta pe mâna ta cea dreaptă. De aceea nu te va bate soarele ziua, nici luna noaptea. (Psalmii 121:5,6)",
"Domnul te va păzi de orice rău, îţi va păzi sufletul. Domnul te va păzi la plecare şi la venire, de acum şi până în veac. (Psalmii 121:7,8)",
"Rugaţi-vă pentru pacea Ierusalimului! Cei ce te iubesc să se bucure de odihnă. (Psalmii 122:6)",
"Cei ce se încred în Domnul sunt ca muntele Sionului care nu se clatină, ci stă întărit pe vecie. (Psalmii 125:1)",
"Cum este înconjurat Ierusalimul de munţi, aşa înconjoară Domnul pe poporul Său, de acum şi până în veac. (Psalmii 125:2)",
"Cei ce seamănă cu lacrimi vor secera cu cântări de veselie. Cel ce umblă plângând, când aruncă sămânţa, se întoarce cu veselie când îşi strânge snopii. (Psalmii 126:5-6)",
"Dacă nu zideşte Domnul o casă, degeaba lucrează cei ce o zidesc; dacă nu păzeşte Domnul o cetate, degeaba veghează cel ce o păzeşte. (Psalmii 127:1)",
"Degeaba vă sculaţi de dimineaţă şi vă culcaţi târziu, ca să mâncaţi o pâine câştigată cu durere; căci preaiubiţilor Lui El le dă pâine ca în somn. (Psalmii 127:2)",
"Iată, fiii sunt o moştenire de la Domnul, rodul pântecelui este o răsplată dată de El. (Psalmii 127:3)",
"Ferice de omul care îşi umple tolba de săgeţi cu ei! Căci ei nu vor rămâne de ruşine când vor vorbi cu vrăjmaşii lor la poartă. (Psalmii 127:5)",
"Ferice de oricine se teme de Domnul şi umblă pe căile Lui! Căci atunci te bucuri de lucrul mâinilor tale, eşti fericit şi-ţi merge bine. (Psalmii 128:1,2)",
"Să te binecuvânteze Domnul din Sion, să vezi fericirea Ierusalimului, în toate zilele vieţii tale, şi să vezi pe copiii copiilor tăi! Pacea să fie peste Israel! (Psalmii 128:5,6)",
"Domnul va sfârși ce a început pentru mine. Doamne, bunătatea Ta ține în veci: nu părăsi lucrările mâinilor Tale. (Psalmii 138:8)",
'Eu zic Domnului: "Tu eşti Dumnezeul meu! Ia aminte, Doamne, la glasul rugăciunilor mele!" (Psalmii 140:6)', "Doamne Dumnezeule, tăria mântuirii mele, Tu-mi acoperi capul în ziua luptei. (Psalmii 140:7)",
"Ştiu că Domnul face dreptate celui asuprit, dreptate, celor lipsiţi. (Psalmii 140:12)",
"Da, cei neprihăniţi vor lăuda Numele Tău, oamenii fără prihană vor locui înaintea Ta. (Psalmii 140:13)",
"Doamne, eu Te chem: vino degrabă la mine! Ia aminte la glasul meu, când Te chem! (Psalmii 141:1)",
"De aceea, către Tine, Doamne Dumnezeule, îmi îndrept ochii, la Tine caut adăpost; nu-mi părăsi sufletul! (Psalmii 141:8)",
"Cu glasul meu strig către Domnul, cu glasul meu mă rog către Domnul. (Psalmii 142:1)",
"Doamne, ascultă-mi rugăciunea, pleacă-Ţi urechea la cererile mele! Ascultă-mă în credincioşia şi dreptatea Ta! (Psalmii 143:1)",
"Mi-aduc aminte de zilele de odinioară, mă gândesc la toate lucrările Tale, cuget la lucrarea mâinilor Tale. (Psalmii 143:5)",
"Fă-mă să aud dis-de-dimineaţă bunătatea Ta, căci mă încred în Tine. Arată-mi calea pe care trebuie să umblu, căci la Tine îmi înalţ sufletul. (Psalmii 143:8)",
"Învaţă-mă să fac voia Ta, căci Tu eşti Dumnezeul meu. Duhul Tău cel bun să mă călăuzească pe calea cea dreaptă! (Psalmii 143:10)",
"Doamne, ce este omul ca să iei cunoştinţă de el, fiul omului ca să iei seama la el? (Psalmii 144:3)",
"Omul este ca o suflare, zilele lui sunt ca umbra care trece. (Psalmii 144:4)",
"Ferice de poporul care stă astfel! Ferice de poporul al cărui Dumnezeu este Domnul! (Psalmii 144:15)",
"Te voi înălţa, Dumnezeule, Împăratul meu, şi voi binecuvânta Numele Tău în veci de veci. (Psalmii 145:1)",
"În fiecare zi Te voi binecuvânta şi voi lăuda Numele Tău în veci de veci. (Psalmii 145:2)",
"Să se trâmbiţeze aducerea aminte de nemărginita Ta bunătate şi să se laude dreptatea Ta! (Psalmii 145:7)",
"Domnul este milostiv şi plin de îndurare, îndelung răbdător şi plin de bunătate. (Psalmii 145:8)",
"Domnul sprijină pe toţi cei ce cad şi îndreaptă pe cei încovoiaţi. (Psalmii 145:14)",
"Ochii tuturor nădăjduiesc în Tine, şi Tu le dai hrana la vreme. (Psalmii 145:15)",
"Îţi deschizi mâna şi saturi după dorinţă tot ce are viaţă. (Psalmii 145:16)",
"Domnul este lângă toţi cei ce-L cheamă, lângă cei ce-L cheamă cu toată inima. (Psalmii 145:18)",
"El împlineşte dorinţele celor ce se tem de El, le aude strigătul şi-i scapă. (Psalmii 145:19)",
"Domnul păzeşte pe toţi cei ce-L iubesc, şi nimiceşte pe toţi cei răi. (Psalmii 145:20)",
"Gura mea să vestească lauda Domnului, şi orice făptură să binecuvânteze Numele Lui cel sfânt, în veci de veci! (Psalmii 145:21)",
"Lăudaţi pe Domnul! Laudă, suflete, pe Domnul! (Psalmii 146:1)",
"Voi lăuda pe Domnul cât voi trăi, voi lăuda pe Dumnezeul meu cât voi fi. (Psalmii 146:2)",
"Lăudaţi pe Domnul! Căci este frumos să lăudăm pe Dumnezeul nostru, căci este plăcut şi se cuvine să-L lăudăm. (Psalmii 147:1)",
"Mare este Domnul nostru şi puternic prin tăria Lui, priceperea Lui este fără margini. (Psalmii 147:5)",
"Domnul iubeşte pe cei ce se tem de El, pe cei ce nădăjduiesc în bunătatea Lui. (Psalmii 147:11)",
"Căci El întăreşte zăvoarele porţilor, El binecuvântă pe fiii tăi în mijlocul tău; El dă pace ţinutului tău şi te satură cu cel mai bun grâu. El Îşi trimite poruncile pe pământ, cuvântul Lui aleargă cu iuţeală mare. El dă zăpada ca lâna, El presară bruma albă ca cenuşa; El Îşi azvârle gheaţa în bucăţi; cine poate sta înaintea frigului Său? El Îşi trimite cuvântul Său şi le topeşte; pune să sufle vântul Lui, şi apele curg. El descoperă lui Iacov cuvântul Său, lui Israel, legile şi poruncile Sale. El n-a lucrat aşa cu toate neamurile, şi ele nu cunosc poruncile Lui. Lăudaţi pe Domnul! (Psalmii 147:13-20)",
"Să salte de bucurie credincioşii Lui, îmbrăcaţi în slavă, să scoată strigăte de bucurie în aşternutul lor! (Psalmii 149:5)",

];
